version: '3'

services:
  web-app:
    build:
      context: ./app
    image: amourance:latest
    ports:
      - "8080:5000"
    volumes:
      - ./:/workspace
      - ./app:/app
    environment:
      - API_TOKEN_NEWS=$API_TOKEN_NEWS
      - API_TOKEN_NINJA=$API_TOKEN_NINJA
