name: Push to feature branch

on:
  push:
    branches:
      - 'feature/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: |
          docker build -t amourance ./app
  test:
    needs: build
    runs-on: ubuntu-latest
    services:
      app:
        image: amourance
    steps:
      - name: Test with pytest
        run: |
          pytest
