name: Merge feature branch to master

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name : Connect Docker Hub
        uses: docker/login-action@v3
        with:
          username:  ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: |
          BRANCH_NAME=$(echo $GITHUB_REF | awk -F'/' '{print $3}')
          COMMIT_HASH=$(echo $GITHUB_SHA | cut -c1-7)
          docker build -t dylanpereira/amourance:$BRANCH_NAME-$COMMIT_HASH ./app
      - name: Push Docker image
        run: |
          BRANCH_NAME=$(echo $GITHUB_REF | awk -F'/' '{print $3}')
          COMMIT_HASH=$(echo $GITHUB_SHA | cut -c1-7)
          docker push dylanpereira/amourance:$BRANCH_NAME-$COMMIT_HASH
      